create table User (
	USERID Integer not null auto_increment,
    USERNAME NVARCHAR(50) NOT NULL,
    PASSWORD NVARCHAR(50) NOT NULL,
    FULLNAME NVARCHAR(50) NOT NULL,
    GENDER NVARCHAR(10) NOT NULL,
    STATE NVARCHAR(50) NOT NULL,
    CITY NVARCHAR(50) NOT NULL,
    STREET NVARCHAR(50) NOT NULL,
    ZIPCODE INTEGER NOT NULL,
    BIRTHDATE DATE NOT NULL,
    EMAIL NVARCHAR(50) NOT NULL,
    ROLE NVARCHAR(10) NOT NULL,
    primary key(USERID)
);
    
